# See https://docs.docker.com/compose/compose-file/03-compose-file/ for best practices
services:
  # FHIR server, auth server and clients to test the servers
  fhir:
    # 2023.3 may not work ...
    image: intersystems/irishealth-community:2023.3
    container_name: fhir
    hostname: fhir
    ports:
      # PWS
    - "58141:52773"
    volumes:
    - type: bind
      source: ./shared-fhir
      target: /shared
    - type: bind
      source: ./src
      target: /src
    environment:
    - ISC_DATA_DIRECTORY=/shared/durable
    - ISC_CPF_MERGE_FILE=/shared/merge.cpf
    command: 
    - -a /shared/configure.sh
 
  # web gateway for fhir
  wg-fhir:
    image: containers.intersystems.com/intersystems/webgateway:latest-cd
    init: true
    container_name: wg-fhir
    hostname: wg-fhir
    ports:
    - "58142:80"
    - "58143:58143"
    environment:
    - ISC_CSP_CONF_FILE=/shared/CSP.conf
    - ISC_CSP_INI_FILE=/shared/CSP.ini
    #- ISC_DATA_DIRECTORY=/wg-shared/durable
    volumes:
    - type: bind
      source: ./shared-wg-fhir
      target: /shared
